spring:
  profiles:
    active: virtualMachine #激活指定环境的profile
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #使用MySQL数据库
    hikari:
      max-lifetime: 60000 #此属性控制池中连接的最大生存期，单位毫秒。参考：https://blog.csdn.net/u013934601/article/details/106085011/
  #配置邮件服务器。参考： https://www.cnblogs.com/zhongyuegang/p/11547232.html
  mail:
    port: 465
    host: smtp.xxx.com #你使用的邮箱服务器域名，例如smtp.qq.com、smtp.163.com。
    username: 你的邮箱账号
    password: 你的邮箱授权码
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true #让服务器检验用户密码是否正确
          #SSL是安全套接层(secure sockets layer)，TLS是SSL的继任者，叫传输层安全(transport layer security)。参考文章： https://blog.csdn.net/ustccw/article/details/76691248
          #SSL相关设置
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory #使用SSL安全连接
            fallback: false #不回退
          #TLS相关设置
          starttls:
            enable: true
            required: true

#服务端口
server:
  port: 80

mybatis:
  config-location: classpath:config/myBatisConfig.xml #指定MyBatis全局配置文件的位置
  mapper-locations: classpath:mapper/**/*.xml #指定SQL映射文件的位置，用逗号可以分隔多个路径，**表示任意层级的目录。

#当前模块信息
info:
  app:
    moduleName: open-note #当前模块名
    region:
      exportPath: output/data/region/regionData.json #地区文件的导出路径，即regionData.json文件。
---
#虚拟机环境-CentOS8
spring:
  profiles: virtualMachine
  datasource:
    #springBoot可以在配置文件中配置数据库连接信息
    username: root
    password: 123456
    url: jdbc:mysql://192.168.64.128:3306/open_note?serverTimezone=UTC
  redis:
    host: 192.168.64.128
    password: 123456

logging:
  level:
    root: info #调整SpringBoot的日志级别